// pinx-ui ships only a *compiled* stylesheet — its @theme source is not in the
// published package (files: ["dist"]). Tailwind needs a real @theme block to
// generate token utilities such as py-extra-large or bg-surface, so we derive
// one from the :root custom properties the package already emits.
//
// Delete this script, the predev/prebuild hooks and src/theme.css as soon as
// pinx-ui exports its @theme source directly.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";

const distCss = fileURLToPath(
  new URL("../node_modules/pinx-ui/dist/index.css", import.meta.url),
);
const out = fileURLToPath(new URL("../src/theme.css", import.meta.url));

const css = readFileSync(distCss, "utf8");
const block = css.match(/:root,\s*:host\s*\{([^}]*)\}/);
if (!block) {
  throw new Error(`No :root token block found in ${distCss}`);
}

const tokens = block[1]
  .split(";")
  .map((decl) => decl.trim())
  .filter((decl) => decl.startsWith("--"));

if (tokens.length === 0) {
  throw new Error(`:root block in ${distCss} declared no custom properties`);
}

// Tailwind inlines shadow values into the utility and omits the --shadow-* var
// from :root, so tokens like --shadow-raised never reach the block above.
// Recover them from the compiled `.shadow-<name>` rules.
const declared = new Set(tokens.map((decl) => decl.split(":")[0].trim()));
for (const [, name, value] of css.matchAll(
  /\.shadow-([\w-]+)\{--tw-shadow:([^;]+);/g,
)) {
  const prop = `--shadow-${name}`;
  if (declared.has(prop)) continue;
  declared.add(prop);
  // Unwrap var(--tw-shadow-color,<colour>) back to the literal colour.
  tokens.push(
    `${prop}:${value.replace(/var\(--tw-shadow-color,([^)]*)\)/g, "$1")}`,
  );
}

mkdirSync(fileURLToPath(new URL("../src", import.meta.url)), { recursive: true });
writeFileSync(
  out,
  [
    "/* GENERATED by scripts/sync-theme.mjs — do not edit.",
    "   Design tokens lifted from pinx-ui's compiled stylesheet. */",
    "@theme {",
    ...tokens.map((decl) => `  ${decl};`),
    "}",
    "",
  ].join("\n"),
);

console.log(`sync-theme: wrote ${tokens.length} tokens to src/theme.css`);
